### PR TITLE
Server

### PR DESCRIPTION
**Pull request by maikoo**
Hi Zach can you please review my PR?

### CODE REVIEW

**Review by zcoursey22 — APPROVED** [review]
Looks good. Consider breaking the PR into multiple more specific PRs. Approved!

**Comment by maikoo** [comment]
@zcoursey22 I made a few more commits in a better commit style can you please check these?

**Review by zcoursey22 — APPROVED** [review]
Looks good. Make sure you remove console.logs before pushing your commits.

**Comment by maikoo** [comment]
Thanks Zach, I have done so!

**Pull request merged**
